<?php

require('cc_config.php');

class couchCurl{
        // if no title provided statement changes to a PUT and the title is generated by couchdb
        static function put($json,$title=NULL,$db=NULL){return self::__cc( ($title == NULL?'POST':'PUT'  ) , ($title==NULL?"'":"/$title'"). " -d \ '$json'",$db);}
        
        static function update($json,$db=NULL){
        // doing it here because of annoying quote bash error for the database..
        	$db = self::___db($db);
        // checking for _id and _rev before attempting a curl..	
        	$doc = json_decode($json);
        	if($doc->_id && $doc->_rev){
        	// probably switch this to _host add content length header??
	        	exec("curl -X PUT -d \ '$json' '".COUCH_SHOST . "/$db/".$doc->_id  ."' -s -H HTTP/1.0 -H ".'"Content-Type: application/json"',$output);
    	    	return $output[0];
        	}else{
        		return "\nMissing _id and/or _rev fields\n";
        	}
        }
        
        static function get($title,$range_stop=FALSE,$db=NULL){return self::__cc('GET',"/$title'",$db);}

        static function delete($title,$rev,$db=NULL){return self::__cc('DELETE',"/$title?rev=$rev'".' -H "Content-Length:1"',$db);}

        static function set_revs_limit($limit=1000,$db=NULL){return(exec('curl -X PUT -d "'.$limit.'" '. "'".COUCH_HOST."/".self::___db($db)."/_revs_limit' -s"));}
	
        static function changes($db=NULL,$options=NULL){return self::__cc('GET',"/_changes".self::___b_opt($options) ."'",$db);}

        static function get_revs_limit($db=NULL){return(self::_host("/".self::___db($db)."/_revs_limit'"));}

        static function all_docs($db=null,$options=null,$ids=null){
        // provide id's as second param (array with strings) if wanting to do a multi doc select
        	return self::__cc( ($ids!=NULL?'POST':'GET')  , "/_all_docs".self::___b_opt($options) .  ($ids!=NULL? "' -d \ '".json_encode(array('keys'=>$ids))."'":"'") ,$db);
        }

   		static function copy($doc,$dest,$rev_id=NULL,$db=NULL){
		  	$query= "/".self::___db($db)."/$doc'". ' -H "Destination: '.$dest.'" -H "Content-Type: application/json"';
			return  self::_host($query,'COPY');
        }
        
        static function copy_to($doc,$dest,$dest_c_rev,$db){
        // Could combine above, but this is easier to understand (experimental...)
        // Provide document id,destination id, and the current ID of that destiation
        // future enhancements could automatically look this up via this library..
		  	$query= "/".self::___db($db)."/$doc'". ' -H "Destination: '.$dest.'?rev='.$dest_c_rev.'" -H "Content-Type: application/json"';
        	return  self::_host($query,'COPY');
        }

        private static function __cc($method='GET',$query,$db=NULL,$no_exe=false){
			$query = "curl -X $method '" . COUCH_HOST."/".self::___db($db)."$query" . ' -s  -H "HTTP/1.0" '. ($method=='PUT' || $method == 'POST'? ' -H "Content-type: application/json"':NULL) ;
			// returns the appropriate curl call, no exe is for debugging (returns the command as a string)
			$result = ($no_exe==false? exec($query,$output):$query);
			// incase we have a resultset with more than a row - otherwise result is permissible
			if(count($output > 1) && is_array($output)) {
					$output = implode('',$output);
					return $output;
			}
			return ($result?$result:($no_exec==true?$query:false));
        }

        private static function _host($call,$method='GET'){
        // provides more direct access to the couch_host for some specific api calls and returns the first element in an array return
        // found in static functions like get_all_dbs , get_revs_limit
			$query = "curl -X $method '" . COUCH_HOST. $call . " -s";
			$result = exec($query,$output);
			return ($output?$output[0]:$result);
        }
        // built to reduce code, checks options array, returns built query if is array, otherwise null
		// used with static functions that allow options
        private static function ___b_opt($options){return ($options!=NULL && is_array($options)? '?'. http_build_query($options):NULL);}
		private static function ___db($db){return ($db == NULL?COUCH_DB :$db);}
}