<?php
/*
	Couch Curl
	Ronaldo Barbachano
	8/11

	Assumes your php has exec() enabled and your php user can use curl.
*/

define('COUCH_HOST','http://localhost:5984');
define('COUCH_DB','test');

class couchCurl{
        // if no title provided statement changes to a PUT and the title is generated by couchdb
        function _cc_put($json,$title=NULL){return self::__cc( ($title == NULL?'POST':'PUT'  ) , ($title==NULL?"'":"/$title'"). " -d \ '$json'");}
        
        function _cc_get($title){return self::__cc('GET',"/$title'");}

        function _cc_delete($title,$rev){return self::__cc('DELETE',"/$title?rev=$rev'");}

        function __cc($method='GET',$query,$no_exe=true){
               $query = "curl -X $method '" . COUCH_HOST."/".COUCH_DB."$query" . ' -s  -H "HTTP/1.0" '. ($method=='PUT' || $method == 'POST'? ' -H "Content-t$
                // returns the appropriate curl call, no exe is for debugging (returns the command as a string)
                $result = ($no_exe==false? exec($query):$query);
                return ($result?$result:($no_exec==true?$query:false));
        }
        
        
/* coming soon...     
// generated commands work - but php wont display them for some reason..
        function _cc_all_docs($by_seq=false){return self::__cc('GET',"/_all_docs'" . ($by_seq?'_by_seq':NULL));}
        function _cc_get_att($title,$name){return self::__cc('GET',"/$title/$name'");}
        function _cc_copy($doc,$dest,$rev_id){
                // COPY /somedatabase/some_doc HTTP/1.1
                // Destination: some_other_doc?rev=rev_id
                // build normal statement then add dest+rev id to header and then exec
                return self::__cc('COPY',"/$doc",false);
        }
*/
}
